// Generated by gencpp from file ibvs_msgs/ImageFeatures.msg
// DO NOT EDIT!


#ifndef IBVS_MSGS_MESSAGE_IMAGEFEATURES_H
#define IBVS_MSGS_MESSAGE_IMAGEFEATURES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace ibvs_msgs
{
template <class ContainerAllocator>
struct ImageFeatures_
{
  typedef ImageFeatures_<ContainerAllocator> Type;

  ImageFeatures_()
    : header()
    , feature_points()
    , feature_velocities()
    , image_jacobian()
    , num_features(0)  {
    }
  ImageFeatures_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , feature_points(_alloc)
    , feature_velocities(_alloc)
    , image_jacobian(_alloc)
    , num_features(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _feature_points_type;
  _feature_points_type feature_points;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _feature_velocities_type;
  _feature_velocities_type feature_velocities;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _image_jacobian_type;
  _image_jacobian_type image_jacobian;

   typedef int32_t _num_features_type;
  _num_features_type num_features;





  typedef boost::shared_ptr< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> const> ConstPtr;

}; // struct ImageFeatures_

typedef ::ibvs_msgs::ImageFeatures_<std::allocator<void> > ImageFeatures;

typedef boost::shared_ptr< ::ibvs_msgs::ImageFeatures > ImageFeaturesPtr;
typedef boost::shared_ptr< ::ibvs_msgs::ImageFeatures const> ImageFeaturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibvs_msgs::ImageFeatures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ibvs_msgs::ImageFeatures_<ContainerAllocator1> & lhs, const ::ibvs_msgs::ImageFeatures_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.feature_points == rhs.feature_points &&
    lhs.feature_velocities == rhs.feature_velocities &&
    lhs.image_jacobian == rhs.image_jacobian &&
    lhs.num_features == rhs.num_features;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ibvs_msgs::ImageFeatures_<ContainerAllocator1> & lhs, const ::ibvs_msgs::ImageFeatures_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ibvs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91c151d3e6d430698eaca9cd7aafd529";
  }

  static const char* value(const ::ibvs_msgs::ImageFeatures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91c151d3e6d43069ULL;
  static const uint64_t static_value2 = 0x8eaca9cd7aafd529ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibvs_msgs/ImageFeatures";
  }

  static const char* value(const ::ibvs_msgs::ImageFeatures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Image feature points\n"
"geometry_msgs/Point[] feature_points\n"
"\n"
"# Feature velocities\n"
"geometry_msgs/Vector3[] feature_velocities\n"
"\n"
"# Image Jacobian matrix (flattened)\n"
"float64[] image_jacobian\n"
"\n"
"# Number of features\n"
"int32 num_features\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ibvs_msgs::ImageFeatures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.feature_points);
      stream.next(m.feature_velocities);
      stream.next(m.image_jacobian);
      stream.next(m.num_features);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageFeatures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibvs_msgs::ImageFeatures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibvs_msgs::ImageFeatures_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feature_points: ";
    if (v.feature_points.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.feature_points.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.feature_points[i]);
    }
    if (v.feature_points.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feature_velocities: ";
    if (v.feature_velocities.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.feature_velocities.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.feature_velocities[i]);
    }
    if (v.feature_velocities.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_jacobian: ";
    if (v.image_jacobian.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.image_jacobian.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.image_jacobian[i]);
    }
    if (v.image_jacobian.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "num_features: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_features);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBVS_MSGS_MESSAGE_IMAGEFEATURES_H
