// Generated by gencpp from file ibvs_msgs/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef IBVS_MSGS_MESSAGE_SETTARGETREQUEST_H
#define IBVS_MSGS_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace ibvs_msgs
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : target_id(0)
    , initial_position()  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : target_id(0)
    , initial_position(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _target_id_type;
  _target_id_type target_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _initial_position_type;
  _initial_position_type initial_position;





  typedef boost::shared_ptr< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::ibvs_msgs::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::ibvs_msgs::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::ibvs_msgs::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator1> & lhs, const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id &&
    lhs.initial_position == rhs.initial_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator1> & lhs, const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ibvs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f993368e0648d1fc78fa6c890bb5fc1";
  }

  static const char* value(const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f993368e0648d1fULL;
  static const uint64_t static_value2 = 0xc78fa6c890bb5fc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibvs_msgs/SetTargetRequest";
  }

  static const char* value(const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
"int32 target_id\n"
"geometry_msgs/Point initial_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
      stream.next(m.initial_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibvs_msgs::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibvs_msgs::SetTargetRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "initial_position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.initial_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBVS_MSGS_MESSAGE_SETTARGETREQUEST_H
