// Generated by gencpp from file ibvs_msgs/SetTarget.msg
// DO NOT EDIT!


#ifndef IBVS_MSGS_MESSAGE_SETTARGET_H
#define IBVS_MSGS_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <ibvs_msgs/SetTargetRequest.h>
#include <ibvs_msgs/SetTargetResponse.h>


namespace ibvs_msgs
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace ibvs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ibvs_msgs::SetTarget > {
  static const char* value()
  {
    return "8cbd1dafdc9b76449a121f5401ae556d";
  }

  static const char* value(const ::ibvs_msgs::SetTarget&) { return value(); }
};

template<>
struct DataType< ::ibvs_msgs::SetTarget > {
  static const char* value()
  {
    return "ibvs_msgs/SetTarget";
  }

  static const char* value(const ::ibvs_msgs::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::ibvs_msgs::SetTargetRequest> should match
// service_traits::MD5Sum< ::ibvs_msgs::SetTarget >
template<>
struct MD5Sum< ::ibvs_msgs::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ibvs_msgs::SetTarget >::value();
  }
  static const char* value(const ::ibvs_msgs::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ibvs_msgs::SetTargetRequest> should match
// service_traits::DataType< ::ibvs_msgs::SetTarget >
template<>
struct DataType< ::ibvs_msgs::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::ibvs_msgs::SetTarget >::value();
  }
  static const char* value(const ::ibvs_msgs::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ibvs_msgs::SetTargetResponse> should match
// service_traits::MD5Sum< ::ibvs_msgs::SetTarget >
template<>
struct MD5Sum< ::ibvs_msgs::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ibvs_msgs::SetTarget >::value();
  }
  static const char* value(const ::ibvs_msgs::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ibvs_msgs::SetTargetResponse> should match
// service_traits::DataType< ::ibvs_msgs::SetTarget >
template<>
struct DataType< ::ibvs_msgs::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::ibvs_msgs::SetTarget >::value();
  }
  static const char* value(const ::ibvs_msgs::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IBVS_MSGS_MESSAGE_SETTARGET_H
