// Generated by gencpp from file ibvs_msgs/TargetState.msg
// DO NOT EDIT!


#ifndef IBVS_MSGS_MESSAGE_TARGETSTATE_H
#define IBVS_MSGS_MESSAGE_TARGETSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace ibvs_msgs
{
template <class ContainerAllocator>
struct TargetState_
{
  typedef TargetState_<ContainerAllocator> Type;

  TargetState_()
    : header()
    , u(0.0)
    , v(0.0)
    , u_dot(0.0)
    , v_dot(0.0)
    , depth(0.0)
    , position()
    , velocity()
    , confidence(0.0)  {
    }
  TargetState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , u(0.0)
    , v(0.0)
    , u_dot(0.0)
    , v_dot(0.0)
    , depth(0.0)
    , position(_alloc)
    , velocity(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _u_dot_type;
  _u_dot_type u_dot;

   typedef double _v_dot_type;
  _v_dot_type v_dot;

   typedef double _depth_type;
  _depth_type depth;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef double _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::ibvs_msgs::TargetState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ibvs_msgs::TargetState_<ContainerAllocator> const> ConstPtr;

}; // struct TargetState_

typedef ::ibvs_msgs::TargetState_<std::allocator<void> > TargetState;

typedef boost::shared_ptr< ::ibvs_msgs::TargetState > TargetStatePtr;
typedef boost::shared_ptr< ::ibvs_msgs::TargetState const> TargetStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ibvs_msgs::TargetState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ibvs_msgs::TargetState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ibvs_msgs::TargetState_<ContainerAllocator1> & lhs, const ::ibvs_msgs::TargetState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.u_dot == rhs.u_dot &&
    lhs.v_dot == rhs.v_dot &&
    lhs.depth == rhs.depth &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ibvs_msgs::TargetState_<ContainerAllocator1> & lhs, const ::ibvs_msgs::TargetState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ibvs_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::TargetState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ibvs_msgs::TargetState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::TargetState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ibvs_msgs::TargetState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::TargetState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ibvs_msgs::TargetState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ibvs_msgs::TargetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c444884cd08771ae2c8b2dd3de8f1d9a";
  }

  static const char* value(const ::ibvs_msgs::TargetState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc444884cd08771aeULL;
  static const uint64_t static_value2 = 0x2c8b2dd3de8f1d9aULL;
};

template<class ContainerAllocator>
struct DataType< ::ibvs_msgs::TargetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ibvs_msgs/TargetState";
  }

  static const char* value(const ::ibvs_msgs::TargetState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ibvs_msgs::TargetState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Target position in image coordinates\n"
"float64 u\n"
"float64 v\n"
"\n"
"# Target velocity in image plane\n"
"float64 u_dot\n"
"float64 v_dot\n"
"\n"
"# Target depth (distance from camera)\n"
"float64 depth\n"
"\n"
"# Target 3D position in camera frame\n"
"geometry_msgs/Point position\n"
"\n"
"# Target 3D velocity in camera frame\n"
"geometry_msgs/Vector3 velocity\n"
"\n"
"# Confidence score\n"
"float64 confidence\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ibvs_msgs::TargetState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ibvs_msgs::TargetState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.u_dot);
      stream.next(m.v_dot);
      stream.next(m.depth);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ibvs_msgs::TargetState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ibvs_msgs::TargetState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "u_dot: ";
    Printer<double>::stream(s, indent + "  ", v.u_dot);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v_dot: ";
    Printer<double>::stream(s, indent + "  ", v.v_dot);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth: ";
    Printer<double>::stream(s, indent + "  ", v.depth);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IBVS_MSGS_MESSAGE_TARGETSTATE_H
